services:
  server:
    container_name: server
    build: ./server
    depends_on:
      - db
    ports:
      - 4001:4001
      - 9229:9229 # debugger port
    volumes:
      - .:/usr/src/app
      - /usr/src/app/.pnpm-store
      - /usr/src/app/node_modules
    command: pnpm start:docker
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres?schema=public
      PORT: 4001
  db:
    container_name: db
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
